# Generated by Django 4.0.5 on 2024-01-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_price',
            field=models.FloatField(default=0.0),
        ),
    ]
