# Generated by Django 4.0.5 on 2024-01-13 04:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_item_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
